config/routes.rb
Rails.application.routes.draw do
  # routes for users via devise
  devise_for :users

  #define scope for i18n
  scope '(:locale)', locale: /en/ do
    # define homepage
    root to: 'pages#home'
    # crud routes for tags
    resources :tags, except: [:index, :show]
    # crud routes for articles
    resources :articles
    # crud routes for entreprises
    resources :entreprises
    # crud routes for readers
    resources :readers, except: [:index, :show, :edit, :update, :destroy]
    # route for positive impact page
    get "/positive-impact", to: 'pages#positive-impact', as: "positiveimpact"
    # route for profile
    get "/profile", to: 'pages#profile', as: "profile"
    # route for contact
    get "/contact", to: 'pages#contact', as: "contact"
    # route for search
    get "/search", to: 'pages#search', as: "search"
    # route for admin
    get "/admin", to: 'admins#admin', as: "admin"
    # route for admin articles
    get "/admin_articles", to: 'admins#articles', as: "admin_articles"
    # route for admin entreprises
    get "/admin_entreprises", to: 'admins#entreprises', as: "admin_entreprises"
    # route for admin tags
    get "/admin_tags", to: 'admins#tags', as: "admin_tags"
    # route for admin contacts
    get "/admin_contacts", to: 'admins#contacts', as: "admin_contacts"
  end
end

app/controllers/entreprises_controller.rb
class EntreprisesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_entreprise, only: [:show, :edit, :update, :destroy]

  def index
    @entreprises = Entreprise.all.order(id: :asc)
  end

  def show
  end

  def new
    @entreprise = Entreprise.new
  end

  def create
    @entreprise = Entreprise.new(entreprise_params)
    if @entreprise.save
      redirect_to admin_entreprises_path, notice: 'Entreprise was succesfully created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @entreprise.update(entreprise_params)
      redirect_to admin_entreprises_path, notice: 'Entreprise was succesfully updated'
    else
      render :edit
    end
  end

  def destroy
    @entreprise.destroy
    redirect_to admin_entreprises_path, notice: 'Entreprise was succesfully destroyed'
  end

  private

  def set_entreprise
    @entreprise = Entreprise.find(params[:id])
  end

  def entreprise_params
    params.require(:entreprise).permit(:name, :value_proposition_fr, :value_proposition_en,
                                       :content_fr, :content_en, :photo, :logo, :website, :tag_id)
  end
end

app/views/entreprises/_form.html.erb
<!-- form to create or edit an entreprise -->
<%= simple_form_for(entreprise) do |f| %>

  <!-- metadata section -->
  <h5 id="form-metadata"><i class="fas fa-exclamation-circle"></i> <%= t('entreprises.form.metadata') %></h5>
  <%= f.input :name, :label => t('entreprises.form.name') %>
  <%= f.input :tag_id, collection: Tag.all.order(name_fr: :asc), label_method: :name_fr, value_method: :id %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.input :logo %>
  <%= f.input :logo_cache, as: :hidden %>
  <%= f.input :website, :label => t('entreprises.form.website') %>

  <!-- entreprise presentation in French -->
  <h5 id="form-french"><i class="fas fa-exclamation-circle"></i> <%= t('entreprises.form.presentation_french') %></h5>
  <h6><%= t('entreprises.form.value_french') %> *</h6>
  <%= f.rich_text_area :value_proposition_fr, :label => t('entreprises.form.value_french') %>
  <h6><%= t('entreprises.form.content_french') %> *</h6>
  <%= f.rich_text_area :content_fr, :label => t('entreprises.form.content_french') %>

  <!-- entreprise presentation in English -->
  <h5 id="form-english"><i class="fas fa-exclamation-circle"></i> <%= t('entreprises.form.presentation_english') %></h5>
  <h6><%= t('entreprises.form.value_english') %> *</h6>
  <%= f.rich_text_area :value_proposition_en, :label => t('entreprises.form.value_english') %>
  <h6><%= t('entreprises.form.content_english') %> *</h6>
  <%= f.rich_text_area :content_en, :label => t('entreprises.form.content_english') %>

  <!-- submit -->
  <%= f.submit t('entreprises.form.save'), class: "button-admin" %>
<% end %>

app/views/entreprises/_menu-new-edit.html.erb
<nav class="top-menu top-menu-admin">
  <!-- link to admin menu -->
  <section class="top-menu-item">
    <%= link_to admin_path do %>
      <%= image_tag('icon_menu_admin.svg') %>
    <% end %>
     <%= link_to admin_path do %>
      <%= t('articles.form.top-menu.admin_page') %>
    <% end %>
  </section>
  <!-- link to metadata -->
  <section class="top-menu-item">
    <a href="#form-metadata"><%= image_tag('icon_menu_metadata.svg') %></a>
    <a href="#form-metadata"><%= t('articles.form.top-menu.metadata') %></a>
  </section>
  <!-- link to french section -->
  <section class="top-menu-item">
    <a href="#form-french"><%= image_tag('icon_menu_france.svg') %></a>
    <a href="#form-french"><%= t('articles.form.top-menu.french') %></a>
  </section>
  <!-- link to english section -->
  <section class="top-menu-item">
    <a href="#form-english"><%= image_tag('icon_menu_english.svg') %></a>
    <a href="#form-english"><%= t('articles.form.top-menu.english') %></a>
  </section>
</nav>

app/views/entreprises/_menu-show.html.erb
<nav class="top-menu">
  <!-- link to entreprise proposition -->
  <section class="top-menu-item">
    <a href="#show-entreprise-intro"><%= image_tag('icon_menu_value-proposition.svg') %></a>
    <a href="#show-entreprise-intro"><%= t('entreprises.top-menu.objective') %></a>
  </section>
  <!-- link to entreprise presentation -->
  <section class="top-menu-item">
    <a href="#show-entreprise-content"><%= image_tag('icon_menu_presentation.svg') %></a>
    <a href="#show-entreprise-content"><%= t('entreprises.top-menu.presentation') %></a>
  </section>
  <!-- link to share entreprise -->
  <section class="top-menu-item">
    <a href="#show-entreprise-share"><%= image_tag('icon_menu_share.svg') %></a>
    <a href="#show-entreprise-share"><%= t('entreprises.top-menu.share') %></a>
  </section>
  <!-- link to entreprise factsheet -->
  <section class="top-menu-item">
    <a href="#show-entreprise-facsheet"><%= image_tag('icon_menu_info.svg') %></a>
    <a href="#show-entreprise-facsheet"><%= t('entreprises.factsheet') %></a>
  </section>
</nav>

app/views/entreprises/edit.html.erb
<!-- customization of the head section -->
<% content_for :head do %>
  <!-- title and name -->
  <title>Blog | Arnaud Rioche | Admin | Edit Entreprise <%= @entreprise.name %></title>
<% end %>

<!-- top menu -->
<%= render 'menu-new-edit' %>

<!-- add spacer for menu -->
<div class="top-menu-spacer"></div>

<!-- form to update an entreprise -->
<main class="container-form">
  <h1><i class="fas fa-user-lock"></i> Modifier une entreprise</h1>
  <%= render 'form', entreprise: @entreprise %>
</main>

app/views/entreprises/index.html.erb
<!-- customization of the head section -->
<% content_for :head do %>
  <!-- title and name -->
  <title>Blog | Arnaud Rioche | Entreprises</title>
  <meta name="description" content="Blog | Arnaud Rioche | Entreprises">
  <!-- Facebook Open Graph data -->
  <meta property="og:title" content=<%= DEFAULT_META["meta_title"] %> />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="<%= request.original_url %>" />
  <meta property="og:image" content=<%= DEFAULT_META["meta_image"] %> />
  <meta property="og:description" content="<%= DEFAULT_META["meta_description"] %>" />
  <meta property="og:site_name" content="<%= DEFAULT_META["meta_site_name"] %>" />
  <!-- Twitter Card data -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
  <meta name="twitter:title" content="<%= DEFAULT_META["meta_title"] %>">
  <meta name="twitter:description" content="<%= DEFAULT_META["meta_description"] %>">
  <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
  <meta name="twitter:image:src" content="<%= DEFAULT_META["meta_image"] %>">
<% end %>

<!-- add spacer for navbar -->
<div class="navbar-banner-spacer"></div>

<!-- define variable for positive impact photo -->
<% @impact = 'img_positiveimpact.jpg' %>

<!-- create banner for the positive impact project -->
<figure class="banner" style="background-image: url('<%= image_path @impact %>')">
  <div class="container-main">
    <!-- positive impac title -->
    <section class="banner-title">
      <%= t('entreprises.positive_impact.title') %>
    </section>
    <!-- positive impact caption -->
    <section class="banner-caption">
      <%= t('entreprises.positive_impact.caption') %>
      <%= link_to t('home.read'), positiveimpact_path %>
    </section>
    <!-- positive impact link to landing page -->
    <button class="button-banner">
      <a href="http://www.google.com" target="_blank"><%= t('entreprises.learn_more') %></a>
    </button>
  </div>
</figure>

<!-- main section to display all entreprises cards -->
<main class="container-main">
  <!-- iterate through all entreprises and create a card for each of them -->
  <% @entreprises.each do |entreprise| %>
    <!-- create a card for each entreprise -->
    <figure class="card-entreprise-index">
      <!-- entreprise logo -->
      <%= cl_image_tag(entreprise.logo) %>
      <!-- entreprise presentation -->
      <figcaption class="card-entreprise-index-presentation">
        <!-- entreprise name -->
        <h1><%= entreprise.name %></h1>
        <!-- display value proposition either in fr or en -->
        <h2>
          <% if I18n.locale == :en %>
            <%= entreprise.value_proposition_en %>
          <% else %>
            <%= entreprise.value_proposition_fr %>
          <% end %>
        </h2>
        <!-- display entreprise content either in fr or en -->
        <p>
          <% if I18n.locale == :en %>
            <%= truncate(strip_tags(entreprise.content_en.to_s), length: 600) %>
          <% else %>
            <%= truncate(strip_tags(entreprise.content_fr.to_s), length: 600) %>
          <% end %>
          <%= link_to t('home.read'), entreprise_path(entreprise) %>
        </p>
        <!-- entreprise link to landing page -->
        <a href="<%= entreprise.website %>" target="_blank"><i class="fas fa-external-link-square-alt"></i>  <%= t('entreprises.learn_more') %></a>
      </figcaption>
    </figure>
  <% end %>
</main>

<!-- footer -->
<%= render 'shared/footer' %>

app/views/entreprises/new.html.erb
!-- customization of the head section -->
<% content_for :head do %>
  <!-- title and name -->
  <title>Blog | Arnaud Rioche | Admin | Create Entreprise</title>
<% end %>

<!-- customization of the head section -->
<% content_for :head do %>
  <!-- title and name -->
  <title>Blog | Arnaud Rioche | Admin | Create Entreprise</title>
<% end %>

<!-- top menu -->
<%= render 'menu-new-edit' %>

<!-- add spacer for menu -->
<div class="top-menu-spacer"></div>

<!-- form to create an entreprise -->
<main class="container-form">
  <h1>Admin | Créer une entreprise</h1>
  <%= render 'form', entreprise: @entreprise %>
</main>

app/views/entreprises/show.html.erb
<!-- define either value proposition in share links must be in en or fr -->
<% I18n.locale == :en ? good_value = @entreprise.value_proposition_en : good_value = @entreprise.value_proposition_fr %>

<!-- define either content in share links must be in en or fr -->
<% I18n.locale == :en ? good_content = @entreprise.content_en : good_content = @entreprise.content_fr %>

<!-- define either introduction body in email share must be in en or fr -->
<% I18n.locale == :en ? intro = "I thought you'd find this entreprise of interest:" : intro = "J'ai pensé que cette entreprise t'intéresserait :" %>

<!-- customization of the head section -->
<% content_for :head do %>
  <!-- title and name -->
  <title>Blog | Arnaud Rioche | <%= @entreprise.name %></title>
  <meta name="description" content="Blog | Arnaud Rioche | <%= @entreprise.name %>">
  <!-- Facebook Open Graph data -->
  <meta property="og:title" content="<%= @entreprise.name %>" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="<%= request.original_url %>" />
  <meta property="og:image" content="<%= image_url(@entreprise.logo) %>" />
  <meta property="og:description" content="<%= truncate(strip_tags(good_content.to_s), length: 100) %>" />
  <meta property="og:site_name" content="<%= DEFAULT_META["meta_site_name"] %>" />
  <!-- Twitter Card data -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
  <meta name="twitter:title" content="<%= @entreprise.name %>">
  <meta name="twitter:description" content="<%= truncate(strip_tags(good_content.to_s), length: 100) %>">
  <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
  <meta name="twitter:image:src" content="<%= image_url(@entreprise.logo) %>">
<% end %>

<!-- top menu -->
<%= render 'menu-show' %>

<!-- add spacer for menu -->
<div class="top-menu-banner-spacer"></div>

<!-- create entreprise banner -->
<figure class="banner" style="background-image: url('<%= cl_image_path @entreprise.photo %>')" id="show-entreprise-intro">
  <div class="container-main">
    <!-- entreprise name -->
    <section class="banner-title">
      <%= @entreprise.name %>
    </section>
    <!-- display entreprise value proposition either in fr or en -->
    <section class="banner-caption">
      <% if I18n.locale == :en %>
         <%= @entreprise.value_proposition_en %>
      <% else %>
         <%= @entreprise.value_proposition_fr %>
      <% end %>
    </section>
    <!-- positive impact link to landing page -->
    <button class="button-banner">
      <a href="<%= @entreprise.website %>" target="_blank"><%= t('entreprises.learn_more') %></a>
    </button>
  </div>
</figure>

<!-- company presentation -->
<main class="container-main">

  <!-- create card for company content either in fr or en -->
  <section class="card-article-show-content" id="show-entreprise-content">
    <% if I18n.locale == :en %>
      <%= @entreprise.content_en %>
    <% else %>
      <%= @entreprise.content_fr %>
    <% end %>
  </section>

  <!-- create card for article share -->
  <section class="card-article-show-share" id="show-entreprise-share">
    <h2><%= t('share.share_entreprise') %></h2>
    <section class="card-article-show-share-medias">
      <!-- linkedin -->
      <a href="https://www.linkedin.com/shareArticle?mini=true&url=<%= request.original_url %>&title=<%= @entreprise.name %>&summary=&source=">
        <i class="fab fa-linkedin"></i>
      </a>
      <!-- viadeo -->
      <a href="http://www.viadeo.com/shareit/share/?url=<%= request.original_url %>&title=<%= @entreprise.name %>">
        <i class="fab fa-viadeo-square"></i>
      </a>
      <!-- twitter -->
      <a href="https://twitter.com/intent/tweet?text=<%= request.original_url %>">
        <i class="fab fa-twitter-square"></i>
      </a>
      <!-- facebook -->
      <a href="https://www.facebook.com/sharer/sharer.php?u=<%= request.original_url %>">
        <i class="fab fa-facebook-square"></i>
      </a>
      <!-- email -->
      <% body = "#{intro}\n\n#{strip_tags(good_value.to_s)}\n\n#{strip_tags(good_content.to_s)}\n\nSite web: #{@entreprise.website}\n\nLire plus sur http://www.arnaudrioche.com" %>
      <%= mail_to "", html_options = {:subject => @entreprise.name, :body => body} do %>
        <i class="fas fa-envelope"></i>
      <% end %>
    </section>
  </section>

  <!-- create card for entreprise factsheet -->
  <section class="card-article-show-readmore" id="show-entreprise-facsheet">
    <h2><%= t('entreprises.factsheet') %></h2>
    <p>Réfléchir à ce que je veux mettre dedans</p>
     <%#= cl_image_tag(@entreprise.logo) %>
  </section>

</main>

<!-- top footer -->
<%= render 'shared/footer' %>