config/routes.rb
Rails.application.routes.draw do
  # routes for users via devise
  devise_for :users

  #define scope for i18n
  scope '(:locale)', locale: /en/ do
    # define homepage
    root to: 'pages#home'
    # crud routes for tags
    resources :tags, except: [:index, :show]
    # crud routes for articles
    resources :articles
    # crud routes for entreprises
    resources :entreprises
    # crud routes for readers
    resources :readers, except: [:index, :show, :edit, :update, :destroy]
    # route for positive impact page
    get "/positive-impact", to: 'pages#positive-impact', as: "positiveimpact"
    # route for profile
    get "/profile", to: 'pages#profile', as: "profile"
    # route for contact
    get "/contact", to: 'pages#contact', as: "contact"
    # route for search
    get "/search", to: 'pages#search', as: "search"
    # route for admin
    get "/admin", to: 'admins#admin', as: "admin"
    # route for admin articles
    get "/admin_articles", to: 'admins#articles', as: "admin_articles"
    # route for admin entreprises
    get "/admin_entreprises", to: 'admins#entreprises', as: "admin_entreprises"
    # route for admin tags
    get "/admin_tags", to: 'admins#tags', as: "admin_tags"
    # route for admin contacts
    get "/admin_contacts", to: 'admins#contacts', as: "admin_contacts"
  end
end

app/views/admins/_menu-admin.html.erb
<nav class="top-menu top-menu-admin">
  <!-- link to admin menu -->
  <section class="top-menu-item">
    <%= link_to admin_path do %>
      <%= image_tag('icon_menu_admin.svg') %>
    <% end %>
     <%= link_to admin_path do %>
      Admin Page
    <% end %>
  </section>
  <!-- link to article admin page -->
  <section class="top-menu-item">
    <%= link_to admin_articles_path do %>
      <%= image_tag('icon_menu_article.svg') %>
    <% end %>
     <%= link_to admin_articles_path do %>
      Articles
    <% end %>
  </section>
  <!-- link to entreprise admin page -->
  <section class="top-menu-item">
     <%= link_to admin_entreprises_path do %>
      <%= image_tag('icon_menu_factory.svg') %>
    <% end %>
     <%= link_to admin_entreprises_path do %>
      Entreprises
    <% end %>
  </section>
  <!-- link to tag admin page -->
  <section class="top-menu-item">
     <%= link_to admin_tags_path do %>
      <%= image_tag('icon_menu_tag.svg') %>
    <% end %>
     <%= link_to admin_tags_path do %>
      Tags
    <% end %>
  </section>
  <!-- link to contact admin page -->
  <section class="top-menu-item">
     <%= link_to admin_contacts_path do %>
      <%= image_tag('icon_menu_reader.svg') %>
    <% end %>
     <%= link_to admin_contacts_path do %>
      Contacts
    <% end %>
  </section>
</nav>

app/views/admins/admin.html.erb
<!-- customization of the head section -->
<% content_for :head do %>
  <!-- title and name -->
  <title>Blog | Arnaud Rioche | Admin | Admin Menu</title>
<% end %>

<!-- top menu -->
<%= render 'menu-admin' %>

<!-- add spacer for menu -->
<div class="top-menu-spacer"></div>

<!-- administration dashboard  -->
<main class="container-main">

  <h1><i class="fas fa-user-lock"></i> <%= t('admin.admin_main') %></h1>

  <!-- accordion to display each admin section -->
  <section class="accordion-admin">
    <ul>
      <!-- contacts -->
      <li>
        <input type="checkbox" checked>
        <i></i>
        <h2>Contacts (<%= @readers.count %>)</h2>
        <p>
          <% @readers.each do |reader| %>
            <%= reader.first_name %> <%= reader.last_name %> |
          <% end %>
        </p>
      </li>
      <!-- articles -->
      <li>
        <input type="checkbox" checked>
        <i></i>
        <h2>Articles (<%= @articles.count %>)</h2>
        <p>
          <% @tags.each do |tag| %>
            <% if I18n.locale == :en %>
              <%= tag.name_en %> : <%= Article.global_search(tag.name_en).count %> |
            <% else %>
              <%= tag.name_fr %> : <%= Article.global_search(tag.name_fr).count %> |
            <% end %>
          <% end %>
        </p>
      </li>
      <!-- entreprises -->
      <li>
        <input type="checkbox" checked>
        <i></i>
        <h2>Entreprises (<%= @entreprises.count %>)</h2>
        <p>
          <% @tags.each do |tag| %>
            <% if I18n.locale == :en %>
              <%= tag.name_en %> : <%= Entreprise.global_search(tag.name_en).count %> |
            <% else %>
              <%= tag.name_fr %> : <%= Entreprise.global_search(tag.name_fr).count %> |
            <% end %>
          <% end %>
        </p>
      </li>
      <!-- tags -->
      <li>
        <input type="checkbox" checked>
        <i></i>
        <h2>Tags (<%= @tags.count %>)</h2>
        <p>
          <% @tags.each do |tag| %>
            <% if I18n.locale == :en %>
              <%= tag.name_en %> |
            <% else %>
              <%= tag.name_fr %> |
            <% end %>
          <% end %>
        </p>
      </li>
      <!-- users -->
      <li>
        <input type="checkbox" checked>
        <i></i>
        <h2>Users (<%= @users.count %>)</h2>
        <p>
          <% @users.each do |user| %>
            <%= user.email %> |
          <% end %>
        </p>
      </li>
    </ul>
  </section>

</main>

app/views/admins/articles.html.erb
<!-- customization of the head section -->
<% content_for :head do %>
  <!-- title and name -->
  <title>Blog | Arnaud Rioche | Admin | Articles</title>
<% end %>

<!-- top menu -->
<%= render 'menu-admin' %>

<!-- add spacer for menu -->
<div class="top-menu-spacer"></div>

<!-- administrate articles  -->
<main class="container-main">

  <h1><i class="fas fa-user-lock"></i> <%= t('admin.admin_articles') %></h1>

  <!-- button to create an article -->
  <button class="button-admin">
    <%= link_to t('admin.create_article'), new_article_path %>
  </button>

  <!-- iterate through all articles and create a card for each of them -->
  <% @articles.each do |article| %>
    <!-- create a card for the article -->
    <figure class="card-article-index">
      <!-- article image -->
      <%= cl_image_tag article.photo, height: 300, width: 400, crop: :fill %>
      <!-- article presentation -->
      <figcaption class="card-article-index-summary">
        <!-- header for date -->
        <div class="card-article-index-header">
          <%= article.date %> |
          <!-- display tag either in fr or en -->
          <% if I18n.locale == :en %>
            <%= article.tag.name_en %>
          <% else %>
            <%= article.tag.name_fr %>
          <% end %>
          <%= article.tag.name_fr %>
        </div>
        <!-- display title either in fr or en -->
        <h2>
          <% if I18n.locale == :en %>
            <%= article.title_en %>
          <% else %>
            <%= article.title_fr %>
          <% end %>
        </h2>
        <!-- display truncated content either in fr or en -->
        <p>
          <% if I18n.locale == :en %>
            <%= truncate(strip_tags(article.content_en.to_s), length: 600) %>
          <% else %>
            <%= truncate(strip_tags(article.content_fr.to_s), length: 600) %>
          <% end %>
        </p>
        <!-- administration links -->
        <div class="card-article-index-admin">
          <!-- see article -->
          <%= link_to article_path(article), target: "_blank" do %>
          <i class="fas fa-eye"></i> <%= t('admin.see') %>
          <% end %>
          <!-- update article -->
          <%= link_to edit_article_path(article) do %>
            <i class="fas fa-edit"></i> <%= t('admin.update') %>
          <% end %>
          <!-- destroy article -->
         <%= link_to article_path(article), method: :delete, data: {confirm: "Supprimer cet article ?"} do %>
          <i class="fas fa-trash"></i> <%= t('admin.destroy') %>
         <% end %>
        </div>
      </figcaption>
    </figure>
  <% end %>

</main>

app/views/admins/contacts.html.erb
<!-- customization of the head section -->
<% content_for :head do %>
  <!-- title and name -->
  <title>Blog | Arnaud Rioche | Admin | Contacts</title>
<% end %>

<!-- top menu -->
<%= render 'menu-admin' %>

<!-- add spacer for menu -->
<div class="top-menu-spacer"></div>

<!-- administrate articles  -->
<main class="container-main">

  <h1><i class="fas fa-user-lock"></i> <%= t('admin.admin_contacts') %></h1>

  <!-- iterate through all readers and create a card for each of them -->
  <% @readers.each do |reader| %>
    <figure class="card-contacts">
      <i class="fas fa-id-card"></i>
      <figcaption class="card-contact-info">
        <h5><%= reader.first_name %>  <%= reader.last_name %></h5>
        <p><%= reader.email %></p>
        <div class="card-contact-info-date">
          <%= reader.created_at %>
        </div>
        <%= reader.message %>
      </figcaption>
    </figure>
  <% end %>

</main>

app/views/admins/entreprises.html.erb
<!-- customization of the head section -->
<% content_for :head do %>
  <!-- title and name -->
  <title>Blog | Arnaud Rioche | Admin | Entreprises</title>
<% end %>

<!-- top menu -->
<%= render 'menu-admin' %>

<!-- add spacer for menu -->
<div class="top-menu-spacer"></div>

<!-- administrate entreprises  -->
<main class="container-main">

  <h1><i class="fas fa-user-lock"></i> <%= t('admin.admin_entreprises') %></h1>

  <!-- button to create an entreprise -->
  <button class="button-admin">
    <%= link_to t('admin.create_entreprise'), new_entreprise_path %>
  </button>

  <!-- iterate through all entreprises and create a card for each of them -->
  <% @entreprises.each do |entreprise| %>
    <!-- create a card for each entreprise -->
    <figure class="card-entreprise-index">
      <!-- entreprise logo -->
      <%= cl_image_tag(entreprise.logo) %>
      <!-- entreprise presentation -->
      <figcaption class="card-entreprise-index-presentation">
        <!-- entreprise name -->
        <h1><%= entreprise.name %></h1>
        <!-- display value proposition either in fr or en -->
        <h2>
          <% if I18n.locale == :en %>
            <%= entreprise.value_proposition_en %>
          <% else %>
            <%= entreprise.value_proposition_fr %>
          <% end %>
        </h2>
        <!-- display entreprise content either in fr or en -->
        <p>
          <% if I18n.locale == :en %>
            <%= truncate(strip_tags(entreprise.content_en.to_s), length: 600) %>
          <% else %>
            <%= truncate(strip_tags(entreprise.content_fr.to_s), length: 600) %>
          <% end %>
        </p>
        <!-- administration links -->
        <div class="card-entreprise-index-admin">
          <!-- see article -->
          <%= link_to entreprise_path(entreprise), target: "_blank" do %>
          <i class="fas fa-eye"></i> <%= t('admin.see') %>
          <% end %>
          <!-- update article -->
          <%= link_to edit_entreprise_path(entreprise) do %>
            <i class="fas fa-edit"></i> <%= t('admin.update') %>
          <% end %>
          <!-- destroy article -->
         <%= link_to entreprise_path(entreprise), method: :delete, data: {confirm: "Supprimer cette entreprise ?"} do %>
          <i class="fas fa-trash"></i> <%= t('admin.destroy') %>
         <% end %>
        </div>
      </figcaption>
    </figure>
  <% end %>
</main>

app/views/admins/tags.html.erb
<!-- customization of the head section -->
<% content_for :head do %>
  <!-- title and name -->
  <title>Blog | Arnaud Rioche | Admin | Tags</title>
<% end %>

<!-- top menu -->
<%= render 'menu-admin' %>

<!-- add spacer for menu -->
<div class="top-menu-spacer"></div>

<!-- administrate tags  -->
<main class="container-main">

  <h1><i class="fas fa-user-lock"></i> <%= t('admin.admin_tags') %></h1>

  <!-- button to create a tag -->
  <button class="button-admin">
    <%= link_to t('admin.create_tag'), new_tag_path %>
  </button>

  <!-- iterate through all tags and create a card for each of them -->
  <% @tags.each do |tag| %>
    <!-- create a card for the tag -->
    <figure class="card-tags">
      <!-- tag icon -->
      <%= cl_image_tag(tag.icon) %>
      <!-- tag information -->
      <figcaption class="card-tags-info">
        <p>FR -- <%= tag.name_fr %></p>
        <p>EN -- <%= tag.name_en %></p>
        <!-- administration links -->
        <div class="card-tags-admin">
          <!-- update tag -->
          <%= link_to edit_tag_path(tag) do %>
            <i class="fas fa-edit"></i> <%= t('admin.update') %>
          <% end %>
          <!-- destroy article -->
          <%= link_to tag_path(tag), method: :delete, data: {confirm: "Supprimer ce tag ?"} do %>
            <i class="fas fa-trash"></i> <%= t('admin.destroy') %>
          <% end %>
        </div>
      </figcaption>
    </figure>
  <% end %>

</main>