config/routes.rb
Rails.application.routes.draw do
  # routes for users via devise
  devise_for :users

  #define scope for i18n
  scope '(:locale)', locale: /en/ do
    # define homepage
    root to: 'pages#home'
    # crud routes for tags
    resources :tags, except: [:index, :show]
    # crud routes for articles
    resources :articles
    # crud routes for entreprises
    resources :entreprises
    # crud routes for readers
    resources :readers, except: [:index, :show, :edit, :update, :destroy]
    # route for positive impact page
    get "/positive-impact", to: 'pages#positive-impact', as: "positiveimpact"
    # route for profile
    get "/profile", to: 'pages#profile', as: "profile"
    # route for contact
    get "/contact", to: 'pages#contact', as: "contact"
    # route for search
    get "/search", to: 'pages#search', as: "search"
    # route for admin
    get "/admin", to: 'admins#admin', as: "admin"
    # route for admin articles
    get "/admin_articles", to: 'admins#articles', as: "admin_articles"
    # route for admin entreprises
    get "/admin_entreprises", to: 'admins#entreprises', as: "admin_entreprises"
    # route for admin tags
    get "/admin_tags", to: 'admins#tags', as: "admin_tags"
    # route for admin contacts
    get "/admin_contacts", to: 'admins#contacts', as: "admin_contacts"
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <p>Copyright 2019 Arnaud Rioche | Crédits photos : unsplash.com</p>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <!-- logo -->
  <section class="navbar-logo">
    <%= link_to root_path do %>
      <div>AR</div>
    <% end %>
  </section>

  <!--  main navbar menu -->
  <section class="navbar-items">
    <!-- articles -->
    <section class="navbar-item">
      <%= link_to articles_path do %>
        <%= image_tag('icon_nav_news.svg') %>
      <% end %>
    </section>
    <!-- entreprises -->
    <section class="navbar-item">
      <%= link_to entreprises_path do %>
        <%= image_tag('icon_nav_startup.svg') %>
      <% end %>
    </section>
    <!-- profile -->
    <section class="navbar-item">
      <%= link_to profile_path do %>
        <%= image_tag('icon_nav_profile.svg') %>
      <% end %>
    </section>
    <!-- contact -->
    <section class="navbar-item">
      <%= link_to contact_path do %>
        <%= image_tag('icon_nav_email.svg') %>
      <% end %>
    </section>
  </section>

  <!-- right-side of the navbar -->
  <section class="navbar-right">
    <section class="navbar-right-search">
      <%= link_to search_path do %>
        <%= image_tag('icon_nav_search.svg') %>
      <% end %>
    </section>
    <section class="navbar-right-language">
      <%= link_to "FR", locale: nil %>
      <%= link_to "EN", locale: "en" %>
    </section>
  </section>

</nav>